In [1]:
import torch
import torch.nn as nn
from modules.module import SMC_Module

%load_ext autoreload
%autoreload 2

DEVICE = torch.device('cuda:0')
b = SMC_Module().to(DEVICE)

T = 64
x = torch.randn(T, 3, 244, 244).to(DEVICE)
x = b(x)



In [20]:
a = [3, 4, 5]
v = nn.Conv1d( sum(a), 12, kernel_size = 3)
v

Conv1d(12, 12, kernel_size=(3,), stride=(1,))

In [ ]:
class TC_Layer(nn.Module):
    
    def __init__(self):
        super(TC_Layer, self).__init__()
        
    def forward(self, x):
        """
        x : T X 256 or 512
        """
        

In [ ]:
class TMC_Block(nn.Module):
    
    def __init__(self):
        super(TMC_Module, self).__init__()
        self.make_module()
        
        
    def forward(self, full, pose, face, hands):
        print("here")
        
    def make_module(self):
        
        intra_Cue = []
        inter_Cue = []
        

In [24]:
c = nn.Conv1d(3, 4, kernel_size=2)
x = torch.ones(1, 3, 7)

print(x)
y = c(x)
print(y.size())
print(y)

tensor([[[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]]])
torch.Size([1, 4, 6])
tensor([[[-0.8604, -0.8604, -0.8604, -0.8604, -0.8604, -0.8604],
         [ 0.3233,  0.3233,  0.3233,  0.3233,  0.3233,  0.3233],
         [ 0.1183,  0.1183,  0.1183,  0.1183,  0.1183,  0.1183],
         [ 0.5857,  0.5857,  0.5857,  0.5857,  0.5857,  0.5857]]],
       grad_fn=<SqueezeBackward1>)


In [25]:
for n, p  in c.named_parameters():
    print(n)
    print(p)

weight
Parameter containing:
tensor([[[-0.2161, -0.3050],
         [ 0.3015, -0.3101],
         [-0.3954,  0.1337]],

        [[-0.1474,  0.0823],
         [ 0.1518,  0.0098],
         [ 0.1986, -0.3169]],

        [[ 0.1044,  0.1543],
         [-0.3745,  0.1018],
         [ 0.2048, -0.2942]],

        [[ 0.3650,  0.0006],
         [-0.0580,  0.2051],
         [-0.1331,  0.3716]]], requires_grad=True)
bias
Parameter containing:
tensor([-0.0691,  0.3450,  0.2217, -0.1655], requires_grad=True)


In [28]:
def make_block(in_channels, out_channels, cue_num):
        
        intra_cue_path = []
        inter_cue_path = []
        
        for i in range(cue_num):
            print(in_channels[i], out_channels/cue_num)
            intra_cue_path.append(nn.Conv1d(in_channels[i], int(out_channels/cue_num), kernel_size = 5, padding = 2))
        intra_cue_path.append(nn.ReLU(inplace=True))
        
        TC_1_layer = nn.Conv1d(out_channels, int(out_channels/2), kernel_size=1)
        
        inter_cue_path.append(nn.Conv1d(sum(in_channels), int(out_channels/2), kernel_size = 5, padding = 2))
        inter_cue_path.append(nn.ReLU(inplace=True))
        
        return nn.ModuleList([nn.ModuleList(intra_cue_path), TC_1_layer, nn.ModuleList(inter_cue_path)])

In [11]:
def a(**kwargs):
    print(kwargs['c'], kwargs['b'])

In [23]:
import torch
b= torch.randn(4, 5, 20, 20)

In [17]:
index = torch.Tensor([[1, 10], [5, 14]])

In [18]:
x[:, :, index[0][0]:index[0][1], index[1][0]:index[1][1]]

TypeError: only integer tensors of a single element can be converted to an index

In [22]:
size = x.size()

In [25]:
size

torch.Size([4, 5, 20, 20])

In [3]:
from torchvision import models
vgg11 = models.vgg11()

In [4]:
vgg11.features[:11]

Sequential(
  (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (1): ReLU(inplace=True)
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (3): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (4): ReLU(inplace=True)
  (5): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (6): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (7): ReLU(inplace=True)
  (8): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (9): ReLU(inplace=True)
  (10): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
)

In [5]:
vgg11.features[11:18]

Sequential(
  (11): Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (12): ReLU(inplace=True)
  (13): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (14): ReLU(inplace=True)
  (15): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (16): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (17): ReLU(inplace=True)
)

In [6]:
vgg11.features[18:]

Sequential(
  (18): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (19): ReLU(inplace=True)
  (20): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
)

In [24]:
import math
def _make_divisible(value, divisor=8):
    new_value = max(divisor, int(value + divisor / 2) // divisor * divisor)
    print("s",new_value)
    if new_value < 0.9 * value:
        new_value += divisor
    print("e",new_value)
    return new_value


def _round_filters(filters, width_mult):
    if width_mult == 1.0:
        return filters
    return int(_make_divisible(filters * width_mult))

def _round_repeats(repeats, depth_mult):
    if depth_mult == 1.0:
        return repeats
    return int(math.ceil(depth_mult * repeats))

In [38]:
import timm

In [46]:
net = timm.create_model('tf_efficientnet_b1')

In [52]:
for layer in net:
    print(layer.__name__)

TypeError: 'EfficientNet' object is not iterable

In [68]:
net.blocks

Sequential(
  (0): Sequential(
    (0): DepthwiseSeparableConv(
      (conv_dw): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=32, bias=False)
      (bn1): BatchNorm2d(32, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
      (act1): SiLU(inplace=True)
      (se): SqueezeExcite(
        (conv_reduce): Conv2d(32, 8, kernel_size=(1, 1), stride=(1, 1))
        (act1): SiLU(inplace=True)
        (conv_expand): Conv2d(8, 32, kernel_size=(1, 1), stride=(1, 1))
        (gate): Sigmoid()
      )
      (conv_pw): Conv2d(32, 16, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn2): BatchNorm2d(16, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
      (act2): Identity()
    )
    (1): DepthwiseSeparableConv(
      (conv_dw): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=16, bias=False)
      (bn1): BatchNorm2d(16, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
      (act1): SiLU(inplace=Tr