In [1]:
import torch
import torch.nn as nn
from modules.module import SMC_Module

%load_ext autoreload
%autoreload 2

DEVICE = torch.device('cuda:0')
b = SMC_Module().to(DEVICE)

T = 64
x = torch.randn(T, 3, 244, 244).to(DEVICE)
x = b(x)



In [20]:
a = [3, 4, 5]
v = nn.Conv1d( sum(a), 12, kernel_size = 3)
v

Conv1d(12, 12, kernel_size=(3,), stride=(1,))

In [ ]:
class TC_Layer(nn.Module):
    
    def __init__(self):
        super(TC_Layer, self).__init__()
        
    def forward(self, x):
        """
        x : T X 256 or 512
        """
        

In [ ]:
class TMC_Block(nn.Module):
    
    def __init__(self):
        super(TMC_Module, self).__init__()
        self.make_module()
        
        
    def forward(self, full, pose, face, hands):
        print("here")
        
    def make_module(self):
        
        intra_Cue = []
        inter_Cue = []
        

In [24]:
c = nn.Conv1d(3, 4, kernel_size=2)
x = torch.ones(1, 3, 7)

print(x)
y = c(x)
print(y.size())
print(y)

tensor([[[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]]])
torch.Size([1, 4, 6])
tensor([[[-0.8604, -0.8604, -0.8604, -0.8604, -0.8604, -0.8604],
         [ 0.3233,  0.3233,  0.3233,  0.3233,  0.3233,  0.3233],
         [ 0.1183,  0.1183,  0.1183,  0.1183,  0.1183,  0.1183],
         [ 0.5857,  0.5857,  0.5857,  0.5857,  0.5857,  0.5857]]],
       grad_fn=<SqueezeBackward1>)


In [25]:
for n, p  in c.named_parameters():
    print(n)
    print(p)

weight
Parameter containing:
tensor([[[-0.2161, -0.3050],
         [ 0.3015, -0.3101],
         [-0.3954,  0.1337]],

        [[-0.1474,  0.0823],
         [ 0.1518,  0.0098],
         [ 0.1986, -0.3169]],

        [[ 0.1044,  0.1543],
         [-0.3745,  0.1018],
         [ 0.2048, -0.2942]],

        [[ 0.3650,  0.0006],
         [-0.0580,  0.2051],
         [-0.1331,  0.3716]]], requires_grad=True)
bias
Parameter containing:
tensor([-0.0691,  0.3450,  0.2217, -0.1655], requires_grad=True)


In [28]:
def make_block(in_channels, out_channels, cue_num):
        
        intra_cue_path = []
        inter_cue_path = []
        
        for i in range(cue_num):
            print(in_channels[i], out_channels/cue_num)
            intra_cue_path.append(nn.Conv1d(in_channels[i], int(out_channels/cue_num), kernel_size = 5, padding = 2))
        intra_cue_path.append(nn.ReLU(inplace=True))
        
        TC_1_layer = nn.Conv1d(out_channels, int(out_channels/2), kernel_size=1)
        
        inter_cue_path.append(nn.Conv1d(sum(in_channels), int(out_channels/2), kernel_size = 5, padding = 2))
        inter_cue_path.append(nn.ReLU(inplace=True))
        
        return nn.ModuleList([nn.ModuleList(intra_cue_path), TC_1_layer, nn.ModuleList(inter_cue_path)])

In [11]:
def a(**kwargs):
    print(kwargs['c'], kwargs['b'])

In [23]:
import torch
b= torch.randn(4, 5, 20, 20)

In [17]:
index = torch.Tensor([[1, 10], [5, 14]])

In [18]:
x[:, :, index[0][0]:index[0][1], index[1][0]:index[1][1]]

TypeError: only integer tensors of a single element can be converted to an index

In [22]:
size = x.size()

In [25]:
size

torch.Size([4, 5, 20, 20])

In [28]:
b.size() == size

True